/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package TRANGCHU;

import DANGNHAP.TAIKHOAN;
import NCCForm.FormNCC;
import PHIEUNHAP.FPhieuNhap;
import QuanLyNhanVien.QuanLyNhanVien;
import TAIKHOAN.FTK;
import TLForm.TLForm;
import doan.QLKH;
import java.awt.BorderLayout;
import java.awt.Color;
import javax.swing.JOptionPane;
import BaoCaoForm.BCForm;
import KMForm.KMForm;
import SachForm.SachForm;

/**
 *
 * @author hoang
 */
public class FChucNangKhac extends javax.swing.JPanel {

    /**
     * Creates new form FChucNangKhac
     */
    TAIKHOAN tk;
    public FChucNangKhac() {
        initComponents();
    }
     public FChucNangKhac(TAIKHOAN in_tk) {
        initComponents();
        tk = in_tk;
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jpnView = new javax.swing.JPanel();
        jpnmenu = new javax.swing.JPanel();
        jpnKH = new javax.swing.JPanel();
        jlbKH = new javax.swing.JLabel();
        jpnNV = new javax.swing.JPanel();
        jlbNV = new javax.swing.JLabel();
        jpnTLS = new javax.swing.JPanel();
        jlbTLS = new javax.swing.JLabel();
        jpnBC = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jpnNCC = new javax.swing.JPanel();
        jlbNCC = new javax.swing.JLabel();
        jpnPN = new javax.swing.JPanel();
        jlbPN = new javax.swing.JLabel();
        jpnTK = new javax.swing.JPanel();
        jlbTK = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jpnTuaDe = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));

        jpnView.setBackground(new java.awt.Color(153, 102, 0));

        jpnmenu.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jpnKH.setBackground(new java.awt.Color(204, 204, 204));
        jpnKH.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jpnKHMouseClicked(evt);
            }
        });

        jlbKH.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jlbKH.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/KH.png"))); // NOI18N
        jlbKH.setText("Khách hàng");

        javax.swing.GroupLayout jpnKHLayout = new javax.swing.GroupLayout(jpnKH);
        jpnKH.setLayout(jpnKHLayout);
        jpnKHLayout.setHorizontalGroup(
            jpnKHLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnKHLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jlbKH, javax.swing.GroupLayout.DEFAULT_SIZE, 249, Short.MAX_VALUE)
                .addContainerGap())
        );
        jpnKHLayout.setVerticalGroup(
            jpnKHLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnKHLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jlbKH)
                .addContainerGap(15, Short.MAX_VALUE))
        );

        jpnNV.setBackground(new java.awt.Color(204, 204, 204));
        jpnNV.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jpnNVMouseClicked(evt);
            }
        });

        jlbNV.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jlbNV.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/nv.png"))); // NOI18N
        jlbNV.setText("Nhân viên");

        javax.swing.GroupLayout jpnNVLayout = new javax.swing.GroupLayout(jpnNV);
        jpnNV.setLayout(jpnNVLayout);
        jpnNVLayout.setHorizontalGroup(
            jpnNVLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnNVLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jlbNV, javax.swing.GroupLayout.DEFAULT_SIZE, 244, Short.MAX_VALUE)
                .addGap(15, 15, 15))
        );
        jpnNVLayout.setVerticalGroup(
            jpnNVLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnNVLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jlbNV)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jpnTLS.setBackground(new java.awt.Color(204, 204, 204));
        jpnTLS.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jpnTLSMouseClicked(evt);
            }
        });

        jlbTLS.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jlbTLS.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/TLoai.png"))); // NOI18N
        jlbTLS.setText("Thể loại sách");

        javax.swing.GroupLayout jpnTLSLayout = new javax.swing.GroupLayout(jpnTLS);
        jpnTLS.setLayout(jpnTLSLayout);
        jpnTLSLayout.setHorizontalGroup(
            jpnTLSLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnTLSLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jlbTLS, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jpnTLSLayout.setVerticalGroup(
            jpnTLSLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnTLSLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jlbTLS)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jpnBC.setBackground(new java.awt.Color(204, 204, 204));
        jpnBC.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jpnBCMouseClicked(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/BaoCao.png"))); // NOI18N
        jLabel6.setText("Báo cáo, thống kê");

        javax.swing.GroupLayout jpnBCLayout = new javax.swing.GroupLayout(jpnBC);
        jpnBC.setLayout(jpnBCLayout);
        jpnBCLayout.setHorizontalGroup(
            jpnBCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnBCLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6)
                .addContainerGap(24, Short.MAX_VALUE))
        );
        jpnBCLayout.setVerticalGroup(
            jpnBCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpnBCLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel6)
                .addGap(15, 15, 15))
        );

        jpnNCC.setBackground(new java.awt.Color(204, 204, 204));
        jpnNCC.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jpnNCCMouseClicked(evt);
            }
        });

        jlbNCC.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jlbNCC.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/NCC.png"))); // NOI18N
        jlbNCC.setText("Nhà cung cấp");

        javax.swing.GroupLayout jpnNCCLayout = new javax.swing.GroupLayout(jpnNCC);
        jpnNCC.setLayout(jpnNCCLayout);
        jpnNCCLayout.setHorizontalGroup(
            jpnNCCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnNCCLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jlbNCC)
                .addContainerGap(62, Short.MAX_VALUE))
        );
        jpnNCCLayout.setVerticalGroup(
            jpnNCCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnNCCLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jlbNCC)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jpnPN.setBackground(new java.awt.Color(204, 204, 204));
        jpnPN.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jpnPNMouseClicked(evt);
            }
        });

        jlbPN.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jlbPN.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/PN.png"))); // NOI18N
        jlbPN.setText("Phiếu nhập sách");

        javax.swing.GroupLayout jpnPNLayout = new javax.swing.GroupLayout(jpnPN);
        jpnPN.setLayout(jpnPNLayout);
        jpnPNLayout.setHorizontalGroup(
            jpnPNLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnPNLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jlbPN, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jpnPNLayout.setVerticalGroup(
            jpnPNLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnPNLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jlbPN)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jpnTK.setBackground(new java.awt.Color(204, 204, 204));
        jpnTK.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jpnTKMouseClicked(evt);
            }
        });

        jlbTK.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jlbTK.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/TK.png"))); // NOI18N
        jlbTK.setText("Tài khoản");

        javax.swing.GroupLayout jpnTKLayout = new javax.swing.GroupLayout(jpnTK);
        jpnTK.setLayout(jpnTKLayout);
        jpnTKLayout.setHorizontalGroup(
            jpnTKLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnTKLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jlbTK, javax.swing.GroupLayout.DEFAULT_SIZE, 270, Short.MAX_VALUE)
                .addContainerGap())
        );
        jpnTKLayout.setVerticalGroup(
            jpnTKLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnTKLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jlbTK)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));
        jPanel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel1MouseClicked(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/QLSach.png"))); // NOI18N
        jLabel1.setText("Sách");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(15, 15, 15))
        );

        jPanel2.setBackground(new java.awt.Color(204, 204, 204));
        jPanel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel2MouseClicked(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/QLKM.png"))); // NOI18N
        jLabel3.setText("Khuyến mãi");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(15, 15, 15))
        );

        javax.swing.GroupLayout jpnmenuLayout = new javax.swing.GroupLayout(jpnmenu);
        jpnmenu.setLayout(jpnmenuLayout);
        jpnmenuLayout.setHorizontalGroup(
            jpnmenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnmenuLayout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(jpnmenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpnmenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jpnNV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jpnKH, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jpnBC, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(60, 60, 60)
                .addGroup(jpnmenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jpnTLS, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jpnNCC, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jpnPN, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(60, 60, 60)
                .addGroup(jpnmenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jpnTK, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(40, 40, 40))
        );
        jpnmenuLayout.setVerticalGroup(
            jpnmenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnmenuLayout.createSequentialGroup()
                .addContainerGap(40, Short.MAX_VALUE)
                .addGroup(jpnmenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jpnKH, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jpnTLS, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jpnTK, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(30, 30, 30)
                .addGroup(jpnmenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jpnNCC, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jpnNV, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(30, 30, 30)
                .addGroup(jpnmenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jpnPN, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jpnBC, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(54, 54, 54))
        );

        jpnTuaDe.setBackground(new java.awt.Color(230, 175, 139));

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("DANH SÁCH CÁC CHỨC NĂNG QUẢN LÝ");

        javax.swing.GroupLayout jpnTuaDeLayout = new javax.swing.GroupLayout(jpnTuaDe);
        jpnTuaDe.setLayout(jpnTuaDeLayout);
        jpnTuaDeLayout.setHorizontalGroup(
            jpnTuaDeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnTuaDeLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jpnTuaDeLayout.setVerticalGroup(
            jpnTuaDeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpnTuaDeLayout.createSequentialGroup()
                .addContainerGap(15, Short.MAX_VALUE)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15))
        );

        javax.swing.GroupLayout jpnViewLayout = new javax.swing.GroupLayout(jpnView);
        jpnView.setLayout(jpnViewLayout);
        jpnViewLayout.setHorizontalGroup(
            jpnViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnViewLayout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(jpnmenu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(50, 50, 50))
            .addComponent(jpnTuaDe, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jpnViewLayout.setVerticalGroup(
            jpnViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnViewLayout.createSequentialGroup()
                .addComponent(jpnTuaDe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 39, Short.MAX_VALUE)
                .addComponent(jpnmenu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jpnView, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jpnView, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(10, 10, 10))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jpnKHMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jpnKHMouseClicked
        // TODO add your handling code here:
        jpnKH.setBackground(new Color(96, 100, 191));
        jlbKH.setBackground(new Color(96, 100, 191));
        jpnView.removeAll();
        jpnView.setLayout(new BorderLayout());
        jpnView.add(new QLKH().getJPN());
        jpnView.validate();
        jpnView.repaint();
    }//GEN-LAST:event_jpnKHMouseClicked

    private void jpnNVMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jpnNVMouseClicked
        // TODO add your handling code here:
        if(tk.getLoaiTK().equals("Quản Lý"));
        else{
            JOptionPane.showMessageDialog(this, "Bạn không có quyền sử dụng chức năng này.");
            return;
        }
        jpnNV.setBackground(new Color(96, 100, 191));
        jlbNV.setBackground(new Color(96, 100, 191));
        jpnView.removeAll();
        jpnView.setLayout(new BorderLayout());
        jpnView.add(new QuanLyNhanVien().getJPN());
        jpnView.validate();
        jpnView.repaint();
    }//GEN-LAST:event_jpnNVMouseClicked

    private void jpnTLSMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jpnTLSMouseClicked
        // TODO add your handling code here:
        jpnTLS.setBackground(new Color(96, 100, 191));
        jlbTLS.setBackground(new Color(96, 100, 191));
        jpnView.removeAll();
        jpnView.setLayout(new BorderLayout());
        jpnView.add(new TLForm().getJPN());
        jpnView.validate();
        jpnView.repaint();
    }//GEN-LAST:event_jpnTLSMouseClicked

    private void jpnNCCMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jpnNCCMouseClicked
        // TODO add your handling code here:
        jpnNCC.setBackground(new Color(96, 100, 191));
        jlbNCC.setBackground(new Color(96, 100, 191));
        jpnView.removeAll();
        jpnView.setLayout(new BorderLayout());
        jpnView.add(new FormNCC().getJPN());
        jpnView.validate();
        jpnView.repaint();
    }//GEN-LAST:event_jpnNCCMouseClicked

    private void jpnPNMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jpnPNMouseClicked
        // TODO add your handling code here:
        jpnPN.setBackground(new Color(96, 100, 191));
        jlbPN.setBackground(new Color(96, 100, 191));
        jpnView.removeAll();
        jpnView.setLayout(new BorderLayout());
        jpnView.add(new FPhieuNhap(tk).getJPN());
        jpnView.validate();
        jpnView.repaint();
    }//GEN-LAST:event_jpnPNMouseClicked

    private void jpnTKMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jpnTKMouseClicked
        // TODO add your handling code here:
        if(tk.getLoaiTK().equals("Quản Lý"));
        else{
            JOptionPane.showMessageDialog(this, "Bạn không có quyền sử dụng chức năng này.");
            return;
        }
        jpnTK.setBackground(new Color(96, 100, 191));
        jlbTK.setBackground(new Color(96, 100, 191));
        jpnView.removeAll();
        jpnView.setLayout(new BorderLayout());
        jpnView.add(new FTK().getJPN());
        jpnView.validate();
        jpnView.repaint();
    }//GEN-LAST:event_jpnTKMouseClicked

    private void jpnBCMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jpnBCMouseClicked
        // TODO add your handling code here:
        if(tk.getLoaiTK().equals("Quản Lý"));
        else{
            JOptionPane.showMessageDialog(this, "Bạn không có quyền sử dụng chức năng này.");
            return;
        }
        jpnTLS.setBackground(new Color(96, 100, 191));
        jlbTLS.setBackground(new Color(96, 100, 191));
        jpnView.removeAll();
        jpnView.setLayout(new BorderLayout());
        jpnView.add(new BCForm().getJPN());
        jpnView.validate();
        jpnView.repaint();
    }//GEN-LAST:event_jpnBCMouseClicked

    private void jPanel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel1MouseClicked
        // TODO add your handling code here:
        jpnTK.setBackground(new Color(96, 100, 191));
        jlbTK.setBackground(new Color(96, 100, 191));
        jpnView.removeAll();
        jpnView.setLayout(new BorderLayout());
        jpnView.add(new SachForm().getJPN());
        jpnView.validate();
        jpnView.repaint();
    }//GEN-LAST:event_jPanel1MouseClicked

    private void jPanel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel2MouseClicked
        // TODO add your handling code here:
        if(tk.getLoaiTK().equals("Quản Lý"));
        else{
            JOptionPane.showMessageDialog(this, "Bạn không có quyền sử dụng chức năng này.");
            return;
        }
        jpnTLS.setBackground(new Color(96, 100, 191));
        jlbTLS.setBackground(new Color(96, 100, 191));
        jpnView.removeAll();
        jpnView.setLayout(new BorderLayout());
        jpnView.add(new KMForm());
        jpnView.validate();
        jpnView.repaint();
    }//GEN-LAST:event_jPanel2MouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel jlbKH;
    private javax.swing.JLabel jlbNCC;
    private javax.swing.JLabel jlbNV;
    private javax.swing.JLabel jlbPN;
    private javax.swing.JLabel jlbTK;
    private javax.swing.JLabel jlbTLS;
    private javax.swing.JPanel jpnBC;
    private javax.swing.JPanel jpnKH;
    private javax.swing.JPanel jpnNCC;
    private javax.swing.JPanel jpnNV;
    private javax.swing.JPanel jpnPN;
    private javax.swing.JPanel jpnTK;
    private javax.swing.JPanel jpnTLS;
    private javax.swing.JPanel jpnTuaDe;
    private javax.swing.JPanel jpnView;
    private javax.swing.JPanel jpnmenu;
    // End of variables declaration//GEN-END:variables
}
