/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package TRANGCHU;
import ChonKM.PnKM;
import ChonSach.PnSach;
import ChonSach.SachFrame;
import DANGNHAP.DangNhap;
import KMForm.KMForm;
import DANGNHAP.TAIKHOAN;
import java.awt.Color; 
/**
 *
 * @author hoang
 */
import HOADON.HOADON;
import ThongTinTK.ThongTin;
import java.awt.BorderLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
public class FTrangChu extends javax.swing.JFrame {

    /**
     * Creates new form FTrangChu
     */
    TAIKHOAN tk;
    public JPanel jpnView2;
    public TAIKHOAN getTK(){
        return tk;
    }
    public FTrangChu() {
        initComponents();
    }
    public JPanel getjpnView(){
        return jpnView2;
    }
    public FTrangChu(TAIKHOAN in_tk) {
        initComponents();
        tk = in_tk;
        jpnView2 = jpnview;
    }
    
    public void LamMoi(){
        jpnCN.setBackground(new Color(0, 102, 102));
        jpnSach.setBackground(new Color(0, 102, 102));
        jpnHD.setBackground(new Color(0, 102, 102));
        jpnKM.setBackground(new Color(0, 102, 102));
        jpnKhac.setBackground(new Color(0, 102, 102));
        jpnTT.setBackground(new Color(0, 102, 102));
        jlbCN.setBackground(new Color(0, 102, 102));
        jlbSach.setBackground(new Color(0, 102, 102));
        jlbHD.setBackground(new Color(0, 102, 102));
        jlbKM.setBackground(new Color(0, 102, 102));
        jlbKhac.setBackground(new Color(0, 102, 102));
        jlbTT.setBackground(new Color(0, 102, 102));
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jpnroot = new javax.swing.JPanel();
        jpnmenu = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jpnCN = new javax.swing.JPanel();
        jlbCN = new javax.swing.JLabel();
        jpnSach = new javax.swing.JPanel();
        jlbSach = new javax.swing.JLabel();
        jpnHD = new javax.swing.JPanel();
        jlbHD = new javax.swing.JLabel();
        jpnKM = new javax.swing.JPanel();
        jlbKM = new javax.swing.JLabel();
        jpnKhac = new javax.swing.JPanel();
        jlbKhac = new javax.swing.JLabel();
        jpnDXuat = new javax.swing.JPanel();
        jlbDXuat = new javax.swing.JLabel();
        jpnTT = new javax.swing.JPanel();
        jlbTT = new javax.swing.JLabel();
        jpnview = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel4 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setFocusCycleRoot(false);

        jpnmenu.setBackground(new java.awt.Color(230, 175, 139));
        jpnmenu.setName("jpnroot"); // NOI18N

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/open-book.png"))); // NOI18N
        jLabel2.setText("jLabel2");

        jpnCN.setBackground(new java.awt.Color(0, 102, 102));
        jpnCN.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jpnCNMouseClicked(evt);
            }
        });

        jlbCN.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        jlbCN.setForeground(new java.awt.Color(255, 255, 255));
        jlbCN.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/user.png"))); // NOI18N
        jlbCN.setText("Cá nhân");

        javax.swing.GroupLayout jpnCNLayout = new javax.swing.GroupLayout(jpnCN);
        jpnCN.setLayout(jpnCNLayout);
        jpnCNLayout.setHorizontalGroup(
            jpnCNLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnCNLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jlbCN, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jpnCNLayout.setVerticalGroup(
            jpnCNLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnCNLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jlbCN, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(15, Short.MAX_VALUE))
        );

        jpnSach.setBackground(new java.awt.Color(0, 102, 102));
        jpnSach.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jpnSachMouseClicked(evt);
            }
        });

        jlbSach.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        jlbSach.setForeground(new java.awt.Color(255, 255, 255));
        jlbSach.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/book-of-black-cover-closed.png"))); // NOI18N
        jlbSach.setText("Sách");

        javax.swing.GroupLayout jpnSachLayout = new javax.swing.GroupLayout(jpnSach);
        jpnSach.setLayout(jpnSachLayout);
        jpnSachLayout.setHorizontalGroup(
            jpnSachLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnSachLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jlbSach, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jpnSachLayout.setVerticalGroup(
            jpnSachLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnSachLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jlbSach, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(15, Short.MAX_VALUE))
        );

        jpnHD.setBackground(new java.awt.Color(0, 102, 102));
        jpnHD.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jpnHDMouseClicked(evt);
            }
        });

        jlbHD.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        jlbHD.setForeground(new java.awt.Color(255, 255, 255));
        jlbHD.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/invoice (1).png"))); // NOI18N
        jlbHD.setText("Hóa đơn");

        javax.swing.GroupLayout jpnHDLayout = new javax.swing.GroupLayout(jpnHD);
        jpnHD.setLayout(jpnHDLayout);
        jpnHDLayout.setHorizontalGroup(
            jpnHDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnHDLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jlbHD, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jpnHDLayout.setVerticalGroup(
            jpnHDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnHDLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jlbHD, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(15, Short.MAX_VALUE))
        );

        jpnKM.setBackground(new java.awt.Color(0, 102, 102));
        jpnKM.setForeground(new java.awt.Color(255, 255, 255));
        jpnKM.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jpnKMMouseClicked(evt);
            }
        });

        jlbKM.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        jlbKM.setForeground(new java.awt.Color(255, 255, 255));
        jlbKM.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/shopping-bag.png"))); // NOI18N
        jlbKM.setText("Khuyến mãi");

        javax.swing.GroupLayout jpnKMLayout = new javax.swing.GroupLayout(jpnKM);
        jpnKM.setLayout(jpnKMLayout);
        jpnKMLayout.setHorizontalGroup(
            jpnKMLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnKMLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jlbKM, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jpnKMLayout.setVerticalGroup(
            jpnKMLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnKMLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jlbKM, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(15, Short.MAX_VALUE))
        );

        jpnKhac.setBackground(new java.awt.Color(0, 102, 102));
        jpnKhac.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jpnKhacMouseClicked(evt);
            }
        });

        jlbKhac.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        jlbKhac.setForeground(new java.awt.Color(255, 255, 255));
        jlbKhac.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/manager.png"))); // NOI18N
        jlbKhac.setText("Quản lý");

        javax.swing.GroupLayout jpnKhacLayout = new javax.swing.GroupLayout(jpnKhac);
        jpnKhac.setLayout(jpnKhacLayout);
        jpnKhacLayout.setHorizontalGroup(
            jpnKhacLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnKhacLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jlbKhac, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jpnKhacLayout.setVerticalGroup(
            jpnKhacLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnKhacLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jlbKhac, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(15, Short.MAX_VALUE))
        );

        jpnDXuat.setBackground(new java.awt.Color(0, 102, 102));
        jpnDXuat.setForeground(new java.awt.Color(255, 255, 255));
        jpnDXuat.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jpnDXuatMouseClicked(evt);
            }
        });

        jlbDXuat.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        jlbDXuat.setForeground(new java.awt.Color(255, 255, 255));
        jlbDXuat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/logout.png"))); // NOI18N
        jlbDXuat.setText("Đăng xuất");

        javax.swing.GroupLayout jpnDXuatLayout = new javax.swing.GroupLayout(jpnDXuat);
        jpnDXuat.setLayout(jpnDXuatLayout);
        jpnDXuatLayout.setHorizontalGroup(
            jpnDXuatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnDXuatLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jlbDXuat, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jpnDXuatLayout.setVerticalGroup(
            jpnDXuatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnDXuatLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jlbDXuat, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jpnTT.setBackground(new java.awt.Color(0, 102, 102));
        jpnTT.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jpnTTMouseClicked(evt);
            }
        });

        jlbTT.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        jlbTT.setForeground(new java.awt.Color(255, 255, 255));
        jlbTT.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/home.png"))); // NOI18N
        jlbTT.setText("Trang Chủ");

        javax.swing.GroupLayout jpnTTLayout = new javax.swing.GroupLayout(jpnTT);
        jpnTT.setLayout(jpnTTLayout);
        jpnTTLayout.setHorizontalGroup(
            jpnTTLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnTTLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jlbTT, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jpnTTLayout.setVerticalGroup(
            jpnTTLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnTTLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jlbTT, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(15, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jpnmenuLayout = new javax.swing.GroupLayout(jpnmenu);
        jpnmenu.setLayout(jpnmenuLayout);
        jpnmenuLayout.setHorizontalGroup(
            jpnmenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnmenuLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpnmenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jpnSach, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jpnHD, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jpnKM, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jpnKhac, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jpnDXuat, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jpnCN, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jpnTT, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jpnmenuLayout.setVerticalGroup(
            jpnmenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnmenuLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jpnTT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jpnCN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jpnSach, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jpnHD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jpnKM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jpnKhac, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jpnDXuat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(82, Short.MAX_VALUE))
        );

        jPanel3.setBackground(new java.awt.Color(230, 175, 139));

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Chào mừng đến với nhà sách Tâm Việt ");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 748, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel3)
                .addContainerGap(15, Short.MAX_VALUE))
        );

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Bìa/Bìa 3.jpg"))); // NOI18N

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Bìa/Bia 4.png"))); // NOI18N

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Bìa/Bia oxfox.jpg"))); // NOI18N

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Bìa/Bia op.jpg"))); // NOI18N
        jLabel7.setText("jLabel7");

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Bìa/Bia YeuEm...jpg"))); // NOI18N
        jLabel8.setText("jLabel8");

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Bìa/Bìa 1_1.jpg"))); // NOI18N
        jLabel9.setText("jLabel9");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(526, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(649, Short.MAX_VALUE))
        );

        jScrollPane1.setViewportView(jPanel4);

        javax.swing.GroupLayout jpnviewLayout = new javax.swing.GroupLayout(jpnview);
        jpnview.setLayout(jpnviewLayout);
        jpnviewLayout.setHorizontalGroup(
            jpnviewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jpnviewLayout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addContainerGap())
        );
        jpnviewLayout.setVerticalGroup(
            jpnviewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnviewLayout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout jpnrootLayout = new javax.swing.GroupLayout(jpnroot);
        jpnroot.setLayout(jpnrootLayout);
        jpnrootLayout.setHorizontalGroup(
            jpnrootLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnrootLayout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(jpnmenu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jpnview, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jpnrootLayout.setVerticalGroup(
            jpnrootLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpnrootLayout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addGroup(jpnrootLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jpnmenu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jpnview, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jpnroot, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jpnroot, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jpnCNMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jpnCNMouseClicked
        // TODO add your handling code here:
        LamMoi();
        jpnCN.setBackground(new Color(96, 100, 191));
        jlbCN.setBackground(new Color(96, 100, 191));
        jpnview.removeAll();
        jpnview.setLayout(new BorderLayout());
        jpnview.add(new ThongTin(tk));
        jpnview.validate();
        jpnview.repaint();
    }//GEN-LAST:event_jpnCNMouseClicked

    private void jpnSachMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jpnSachMouseClicked
        // TODO add your handling code here:
        LamMoi();
        jpnSach.setBackground(new Color(96, 100, 191));
        jlbSach.setBackground(new Color(96, 100, 191));
        jpnview.removeAll();
        jpnview.setLayout(new BorderLayout());
        jpnview.add(new PnSach());
        jpnview.validate();
        jpnview.repaint();
    }//GEN-LAST:event_jpnSachMouseClicked

    private void jpnHDMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jpnHDMouseClicked
        // TODO add your handling code here:
        LamMoi();
        jpnHD.setBackground(new Color(96, 100, 191));
        jlbHD.setBackground(new Color(96, 100, 191));
        jpnview.removeAll();
        jpnview.setLayout(new BorderLayout());
        jpnview.add(new HOADON(tk).getJPN());
        jpnview.validate();
        jpnview.repaint();
    }//GEN-LAST:event_jpnHDMouseClicked

    private void jpnKMMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jpnKMMouseClicked
        // TODO add your handling code here:
        LamMoi();
        jpnKM.setBackground(new Color(96, 100, 191));
        jlbKM.setBackground(new Color(96, 100, 191));
        jpnview.removeAll();
        jpnview.setLayout(new BorderLayout());
        jpnview.add(new PnKM());
        jpnview.validate();
        jpnview.repaint();
    }//GEN-LAST:event_jpnKMMouseClicked

    private void jpnKhacMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jpnKhacMouseClicked
        // TODO add your handling code here:
        LamMoi();
        jpnKhac.setBackground(new Color(96, 100, 191));
        jlbKhac.setBackground(new Color(96, 100, 191));
        jpnview.removeAll();
        jpnview.setLayout(new BorderLayout());
        jpnview.add(new FChucNangKhac(tk));
        jpnview.validate();
        jpnview.repaint();
    }//GEN-LAST:event_jpnKhacMouseClicked

    private void jpnDXuatMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jpnDXuatMouseClicked
        // TODO add your handling code here:
        int result = JOptionPane.showConfirmDialog(this,"Bạn có muốn đăng xuất không?","xác nhận", JOptionPane.YES_NO_OPTION);
        if (result == JOptionPane.YES_OPTION){
            new DangNhap().setVisible(true);
            this.dispose();
        }
    }//GEN-LAST:event_jpnDXuatMouseClicked

    private void jpnTTMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jpnTTMouseClicked
        // TODO add your handling code here:
        LamMoi();
        jpnTT.setBackground(new Color(96, 100, 191));
        jlbTT.setBackground(new Color(96, 100, 191));
        jpnview.removeAll();
        jpnview.setLayout(new BorderLayout());
        jpnview.add(new FTrangChu(tk).getjpnView());
        jpnview.validate();
        jpnview.repaint();
    }//GEN-LAST:event_jpnTTMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FTrangChu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FTrangChu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FTrangChu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FTrangChu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FTrangChu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel jlbCN;
    private javax.swing.JLabel jlbDXuat;
    private javax.swing.JLabel jlbHD;
    private javax.swing.JLabel jlbKM;
    private javax.swing.JLabel jlbKhac;
    private javax.swing.JLabel jlbSach;
    private javax.swing.JLabel jlbTT;
    private javax.swing.JPanel jpnCN;
    private javax.swing.JPanel jpnDXuat;
    private javax.swing.JPanel jpnHD;
    private javax.swing.JPanel jpnKM;
    private javax.swing.JPanel jpnKhac;
    private javax.swing.JPanel jpnSach;
    private javax.swing.JPanel jpnTT;
    private javax.swing.JPanel jpnmenu;
    private javax.swing.JPanel jpnroot;
    private javax.swing.JPanel jpnview;
    // End of variables declaration//GEN-END:variables
}
