/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package HOADON;
import ChonSach.SachFrame;
import doan.JDBCConnection;
import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.event.KeyEvent;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.List;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import java.sql.Connection;
import java.sql.*;
import javax.swing.JPanel;



/**
 *
 * @author hoang
 */
public class CTHD extends javax.swing.JFrame {

    /**
     * Creates new form CTHD
     */
    String MaHD;
    Connection conn;
    PreparedStatement ps;
    ResultSet rs;
    public CTHD() {
        initComponents();
        KetNoiCSDL();
        Load_data_CTHD();
        setVisible(true);
    }
    public CTHD(String in_MaHD) {
        initComponents();
        KetNoiCSDL();
        Load_data_CTHD(in_MaHD);
        MaHD = in_MaHD;
        jMaHD.setText(in_MaHD);
    }
    public JPanel getJPN(){
        return jpnCTHD;
    }
    public void NhanDLMaSach(String MaSach){
        jMaSach.setText(MaSach);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jpnCTHD = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jMaSach = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        listCTHD = new javax.swing.JTable();
        jSoLuong = new javax.swing.JSpinner();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jButton5 = new javax.swing.JButton();
        jMaHD = new javax.swing.JLabel();
        jButtonChonSach = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel2.setText("Mã hóa đơn");

        jLabel3.setText("Mã sách");

        jMaSach.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMaSachActionPerformed(evt);
            }
        });

        jLabel4.setText("Số lượng");

        jButton1.setBackground(new java.awt.Color(230, 175, 139));
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Add-icon.png"))); // NOI18N
        jButton1.setText("Thêm");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setBackground(new java.awt.Color(230, 175, 139));
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Trash-can-icon.png"))); // NOI18N
        jButton2.setText("Xóa");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setBackground(new java.awt.Color(230, 175, 139));
        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/edit.png"))); // NOI18N
        jButton3.setText("Cập nhật");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setBackground(new java.awt.Color(230, 175, 139));
        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/arrow-circle-right-icon.png"))); // NOI18N
        jButton4.setText("Reset");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        listCTHD.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã hóa đơn", "Mã sách", "Tên sách", "Số lượng", "Thành tiền"
            }
        ));
        listCTHD.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                listCTHDMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(listCTHD);

        jPanel1.setBackground(new java.awt.Color(230, 175, 139));
        jPanel1.setRequestFocusEnabled(false);

        jLabel1.setBackground(new java.awt.Color(102, 255, 255));
        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("CHI TIẾT HÓA ĐƠN");

        jButton5.setBackground(new java.awt.Color(255, 102, 51));
        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/exit.png"))); // NOI18N
        jButton5.setText("Trở lại");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jButton5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 634, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jButton5)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(19, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addContainerGap())
        );

        jButtonChonSach.setText("...");
        jButtonChonSach.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonChonSachActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jpnCTHDLayout = new javax.swing.GroupLayout(jpnCTHD);
        jpnCTHD.setLayout(jpnCTHDLayout);
        jpnCTHDLayout.setHorizontalGroup(
            jpnCTHDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnCTHDLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(jpnCTHDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpnCTHDLayout.createSequentialGroup()
                        .addGroup(jpnCTHDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jpnCTHDLayout.createSequentialGroup()
                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jSoLuong, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jpnCTHDLayout.createSequentialGroup()
                                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jpnCTHDLayout.createSequentialGroup()
                        .addGroup(jpnCTHDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jpnCTHDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jMaSach, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
                            .addComponent(jMaHD, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonChonSach, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(30, 30, 30)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addContainerGap())
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jpnCTHDLayout.setVerticalGroup(
            jpnCTHDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnCTHDLayout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addGroup(jpnCTHDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpnCTHDLayout.createSequentialGroup()
                        .addGroup(jpnCTHDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jMaHD, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jpnCTHDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jMaSach, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButtonChonSach))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jpnCTHDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jSoLuong, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jpnCTHDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jpnCTHD, javax.swing.GroupLayout.PREFERRED_SIZE, 102, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jpnCTHD, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        LamMoi();
        Load_data_CTHD(MaHD);
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        jpnCTHD.removeAll();
        jpnCTHD.setLayout(new BorderLayout());
        jpnCTHD.add(new HOADON().getJPN());
        jpnCTHD.validate();
        jpnCTHD.repaint();
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        StringBuilder sb1 = new StringBuilder();
        if(jMaHD.getText().equals("") ){
            sb1.append("!!Mã hóa đơn không được để trống!!");
            jMaHD.setBackground(Color.red);
        }
        else{
            jMaHD.setBackground(Color.white);
        }
        StringBuilder sb2 = new StringBuilder();
        if(jMaSach.getText().equals("")){
            sb2.append("!!Mã sách không được để trống!!");
            jMaSach.setBackground(Color.red);
        }
        else{
            jMaSach.setBackground(Color.white);
        }
        if(sb1.length() > 0 || sb2.length() > 0){
            JOptionPane.showMessageDialog(this, sb1 + "\n" + sb2);
            return;
        }
        try{
            int result = JOptionPane.showConfirmDialog(null,"Bạn có muốn xóa chi tiết hóa đơn?", "Xóa", JOptionPane.YES_NO_OPTION);
            if(result == JOptionPane.YES_OPTION){
                CTHDmodify.DeleteCTHD(jMaHD.getText(), jMaSach.getText());
                JOptionPane.showMessageDialog(this,"Đã xóa chi tiết hóa đơn thành công");
            }
            else{
                JOptionPane.showMessageDialog(this,"Chi tiết hóa đơn chưa được xóa");
            }
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(this,"Error : "+e.getMessage());
            e.printStackTrace();
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        StringBuilder sb1 = new StringBuilder();
        if(jMaHD.getText().equals("") ){
            sb1.append("!!Mã hóa đơn không được để trống!!");
            jMaHD.setBackground(Color.red);
        }
        else{
            jMaHD.setBackground(Color.white);
        }
        StringBuilder sb2 = new StringBuilder();
        if(jMaSach.getText().equals("")){
            sb2.append("!!Mã sách không được để trống!!");
            jMaSach.setBackground(Color.red);
        }
        else{
            jMaSach.setBackground(Color.white);
        }
        if(sb1.length() > 0 || sb2.length() > 0){
            JOptionPane.showMessageDialog(this, sb1 + "\n" + sb2);
            return;
        }
        if((int)jSoLuong.getValue() < 0){
            JOptionPane.showMessageDialog(this, "Số lượng không được âm");
            return;
        }
        try{
           Connection connection = JDBCConnection.getJDBCConnection();
           String sql = "{call Them_CTHD(?,?,?)}";
          
           CallableStatement cs = connection.prepareCall(sql);      
           cs.setString(1,jMaHD.getText());
           cs.setString(2,jMaSach.getText());
           cs.setInt(3, (int) jSoLuong.getValue());
           cs.execute();
           JOptionPane.showMessageDialog(this,"Đã thêm thành công");
       }
        catch(SQLException ex){
            JOptionPane.showMessageDialog(this,"Error :"+ ex.getMessage());
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
         StringBuilder sb1 = new StringBuilder();
        if(jMaHD.getText().equals("") ){
            sb1.append("!!Mã hóa đơn không được để trống!!");
            jMaHD.setBackground(Color.red);
        }
        else{
            jMaHD.setBackground(Color.white);
        }
        StringBuilder sb2 = new StringBuilder();
        if(jMaSach.getText().equals("")){
            sb2.append("!!Mã sách không được để trống!!");
            jMaSach.setBackground(Color.red);
        }
        else{
            jMaSach.setBackground(Color.white);
        }
        if(sb1.length() > 0 || sb2.length() > 0){
            JOptionPane.showMessageDialog(this, sb1 + "\n" + sb2);
            return;
        }
        if((int)jSoLuong.getValue() < 0){
            JOptionPane.showMessageDialog(this, "Số lượng không được âm");
            return;
        }
        try{
           int result = JOptionPane.showConfirmDialog(null,"Bạn có muốn cập nhật?", "Cập nhật", JOptionPane.YES_NO_OPTION);
            if(result == JOptionPane.YES_OPTION){ 
                Connection connection = JDBCConnection.getJDBCConnection();
                String sql = "{call Cap_Nhat_CTHD(?,?,?)}";

                CallableStatement cs = connection.prepareCall(sql);      
                cs.setString(1,jMaHD.getText());
                cs.setString(2,jMaSach.getText());
                cs.setInt(3, (int) jSoLuong.getValue());
                cs.execute();
                JOptionPane.showMessageDialog(this, "Cập nhật thành công");
            }
            else JOptionPane.showMessageDialog(this, "Chưa Cập nhật");
       }
        catch(SQLException ex){
            JOptionPane.showMessageDialog(this,"Error :"+ ex.getMessage());
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void listCTHDMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_listCTHDMouseClicked
        // TODO add your handling code here:
        LamMoi();
        try{
        int selectedIndex = listCTHD.getSelectedRow();
        jMaHD.setText(listCTHD.getValueAt(selectedIndex, 0).toString());
        jMaSach.setText(listCTHD.getValueAt(selectedIndex, 1).toString());
        jSoLuong.setValue(Integer.parseInt(listCTHD.getValueAt(selectedIndex, 3).toString()));
        }
        catch(Exception e){
            JOptionPane.showConfirmDialog(this, "Error : " + e.getMessage());
        }
    }//GEN-LAST:event_listCTHDMouseClicked

    private void jMaSachActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMaSachActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMaSachActionPerformed

    private void jButtonChonSachActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonChonSachActionPerformed
        // TODO add your handling code here:
        SachFrame sf = new SachFrame();
        sf.setVisible(true);
        String KT = "cthd";
        sf.TruyenDL(this, KT);
    }//GEN-LAST:event_jButtonChonSachActionPerformed

    /**
     * @param args the command line arguments
     */
    
    public void KetNoiCSDL(){ 
        try {
        Class.forName("oracle.jdbc.driver.OracleDriver");
        System.out.print("Ket noi thanh cong");
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(CTHD.class.getName()).log(Level.SEVERE, null, ex);
        }
        try {
            
           conn = DriverManager.getConnection("jdbc:oracle:thin:@localhost:1521:orcl","DoAn", "doan");
        
        } catch (SQLException ex) {
            Logger.getLogger(CTHD.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }
    public void Load_data_CTHD(){
        try{
            ps = conn.prepareStatement("SELECT ct.MaHD, ct.MaSach, s.TenSach, ct.SoLuong, ct.ThanhTien "
                                        + "FROM CTHD ct, SACH s "
                                        + "WHERE ct.MaSach = s.MaSach");
            rs = ps.executeQuery();

            ResultSetMetaData rsd = rs.getMetaData();
            int c = rsd.getColumnCount();

            DefaultTableModel model = (DefaultTableModel) listCTHD.getModel();
            model.setRowCount(0);
            while (rs.next()){
                    Vector v1 = new Vector();
                    for(int i=1;i<=c;i++){
                        v1.add(rs.getString("MaHD"));
                        v1.add(rs.getString("MaSach"));
                        v1.add(rs.getString("TenSach"));
                        v1.add(rs.getInt("SoLuong"));
                        v1.add(rs.getFloat("ThanhTien"));
                  }
                    model.addRow(v1);
                   listCTHD.setModel(model);
                }
        }
        catch (SQLException ex){
            Logger.getLogger(CTHD.class.getName()).log(Level.SEVERE, null, ex);
        }     
    }
    
    public void Load_data_CTHD(String MaHD){
        try{
            ps = conn.prepareStatement("SELECT ct.MaHD, ct.MaSach, s.TenSach, ct.SoLuong, ct.ThanhTien "
                                        + "FROM CTHD ct, SACH s "
                                        + "WHERE ct.MaSach = s.MaSach and MaHD = ?");
            ps.setString(1, MaHD);
            rs = ps.executeQuery();

            ResultSetMetaData rsd = rs.getMetaData();
            int c = rsd.getColumnCount();

            DefaultTableModel model = (DefaultTableModel) listCTHD.getModel();
            model.setRowCount(0);
            while (rs.next()){
                    Vector v1 = new Vector();
                    for(int i=1;i<=c;i++){
                        v1.add(rs.getString("MaHD"));
                        v1.add(rs.getString("MaSach"));
                        v1.add(rs.getString("TenSach"));
                        v1.add(rs.getInt("SoLuong"));
                        v1.add(rs.getFloat("ThanhTien"));
                  }
                    model.addRow(v1);
                   listCTHD.setModel(model);
                }
        }
        catch (SQLException ex){
            Logger.getLogger(CTHD.class.getName()).log(Level.SEVERE, null, ex);
        }     
    }
    
    public void LamMoi(){
        jMaSach.setText("");
        jSoLuong.setValue(0);
    }
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CTHD.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CTHD.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CTHD.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CTHD.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CTHD().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButtonChonSach;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jMaHD;
    private javax.swing.JTextField jMaSach;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSpinner jSoLuong;
    private javax.swing.JPanel jpnCTHD;
    private javax.swing.JTable listCTHD;
    // End of variables declaration//GEN-END:variables
}
